{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "api-to-splunk.fullname" . }}
  labels:
    {{- include "api-to-splunk.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "api-to-splunk.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - podSelector: {}
  egress:
    - to:
        - ipBlock:
            cidr: 0.0.0.0/0
      ports:
        - protocol: UDP
          port: 53
    {{- if .Values.networkPolicy.splunkHecCidrs }}
    {{- range .Values.networkPolicy.splunkHecCidrs }}
    - to:
        - ipBlock:
            cidr: {{ . | quote }}
      ports:
        - protocol: TCP
          port: 8088
    {{- end }}
    {{- end }}
    {{- range .Values.networkPolicy.apiEndpointCidrs }}
    - to:
        - ipBlock:
            cidr: {{ . | quote }}
      ports:
        - protocol: TCP
          port: 443
    {{- end }}
{{- end }}
