apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "api-to-splunk.fullname" . }}-spool
  labels:
    {{- include "api-to-splunk.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.pvc.size }}
  {{- if .Values.pvc.storageClassName }}
  storageClassName: {{ .Values.pvc.storageClassName }}
  {{- end }}
