apiVersion: v1
kind: Service
metadata:
  name: {{ include "api-to-splunk.fullname" . }}
  labels:
    {{- include "api-to-splunk.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: poller-health
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
    - name: sender-health
      port: 8081
      targetPort: 8081
      protocol: TCP
  selector:
    {{- include "api-to-splunk.selectorLabels" . | nindent 4 }}
