apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: api-to-splunk-hmc
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: site-mon=ghcr.io/yonatan895/site_mon/site-mon
    argocd-image-updater.argoproj.io/site-mon.update-strategy: semver
    argocd-image-updater.argoproj.io/site-mon.helm.image-tag: image.tag
spec:
  project: default
  source:
    repoURL: https://git.internal.example.com/monitoring/api-to-splunk.git
    targetRevision: main
    path: charts/api-to-splunk
    helm:
      valueFiles:
        - values.yaml
        - values-prod.yaml
      values: |
        global:
          platform: hmc
        vault:
          secretName: "api-to-splunk-hmc-secrets"
        networkPolicy:
          splunkHecCidrs: []
          apiEndpointCidrs: []
  destination:
    server: https://kubernetes.default.svc
    namespace: mainframe-monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
