apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: api-to-splunk-csm-secrets
  namespace: mainframe-monitoring
spec:
  refreshInterval: "5m"
  secretStoreRef:
    name: mainframe-vault-store
    kind: SecretStore
  target:
    name: api-to-splunk-csm-secrets
    creationPolicy: Owner
  data:
    - secretKey: SPLUNK_HEC_TOKEN
      remoteRef:
        key: "secret/mainframe/splunk/hec"
        property: hec_token
    - secretKey: CSM_MAIN_USERNAME
      remoteRef:
        key: "secret/mainframe/csm/main"
        property: csm_main_user
    - secretKey: CSM_MAIN_PASSWORD
      remoteRef:
        key: "secret/mainframe/csm/main"
        property: csm_main_pass
    - secretKey: CSM_DR_USERNAME
      remoteRef:
        key: "secret/mainframe/csm/dr"
        property: csm_dr_user
    - secretKey: CSM_DR_PASSWORD
      remoteRef:
        key: "secret/mainframe/csm/dr"
        property: csm_dr_pass
