apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: api-to-splunk-hmc-secrets
  namespace: mainframe-monitoring
spec:
  refreshInterval: "5m"
  secretStoreRef:
    name: mainframe-vault-store
    kind: SecretStore
  target:
    name: api-to-splunk-hmc-secrets
    creationPolicy: Owner
  data:
    - secretKey: SPLUNK_HEC_TOKEN
      remoteRef:
        key: "secret/mainframe/splunk/hec"
        property: hec_token
    - secretKey: HMC_PRIMARY_USERNAME
      remoteRef:
        key: "secret/mainframe/hmc/primary"
        property: hmc_primary_user
    - secretKey: HMC_PRIMARY_PASSWORD
      remoteRef:
        key: "secret/mainframe/hmc/primary"
        property: hmc_primary_pass
    - secretKey: HMC_BACKUP_USERNAME
      remoteRef:
        key: "secret/mainframe/hmc/backup"
        property: hmc_backup_user
    - secretKey: HMC_BACKUP_PASSWORD
      remoteRef:
        key: "secret/mainframe/hmc/backup"
        property: hmc_backup_pass
