apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: api-to-splunk-ds-secrets
  namespace: mainframe-monitoring
spec:
  refreshInterval: "5m"
  secretStoreRef:
    name: mainframe-vault-store
    kind: SecretStore
  target:
    name: api-to-splunk-ds-secrets
    creationPolicy: Owner
  data:
    - secretKey: SPLUNK_HEC_TOKEN
      remoteRef:
        key: "secret/mainframe/splunk/hec"
        property: hec_token
    - secretKey: DS_MAIN_USERNAME
      remoteRef:
        key: "secret/mainframe/ds/main"
        property: ds_main_user
    - secretKey: DS_MAIN_PASSWORD
      remoteRef:
        key: "secret/mainframe/ds/main"
        property: ds_main_pass
    - secretKey: DS_DR_USERNAME
      remoteRef:
        key: "secret/mainframe/ds/dr"
        property: ds_dr_user
    - secretKey: DS_DR_PASSWORD
      remoteRef:
        key: "secret/mainframe/ds/dr"
        property: ds_dr_pass
