apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: api-to-splunk-ts7700-secrets
  namespace: mainframe-monitoring
spec:
  refreshInterval: "5m"
  secretStoreRef:
    name: mainframe-vault-store
    kind: SecretStore
  target:
    name: api-to-splunk-ts7700-secrets
    creationPolicy: Owner
  data:
    - secretKey: SPLUNK_HEC_TOKEN
      remoteRef:
        key: "secret/mainframe/splunk/hec"
        property: hec_token
    - secretKey: TS7700_PRIMARY_USERNAME
      remoteRef:
        key: "secret/mainframe/ts7700/primary"
        property: ts7700_primary_user
    - secretKey: TS7700_PRIMARY_PASSWORD
      remoteRef:
        key: "secret/mainframe/ts7700/primary"
        property: ts7700_primary_pass
    - secretKey: TS7700_BACKUP_USERNAME
      remoteRef:
        key: "secret/mainframe/ts7700/backup"
        property: ts7700_backup_user
    - secretKey: TS7700_BACKUP_PASSWORD
      remoteRef:
        key: "secret/mainframe/ts7700/backup"
        property: ts7700_backup_pass
