apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: mainframe-vault-store
  namespace: mainframe-monitoring
spec:
  provider:
    vault:
      server: "https://vault.internal.example.com"
      path: "mainframe"
      version: "v2"
      auth:
        kubernetes:
          mountPath: "kubernetes"
          role: "mainframe-monitoring"
          serviceAccountRef:
            name: "api-to-splunk-sa"
