apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: api-to-splunk-secrets
  namespace: mainframe-monitoring
spec:
  refreshInterval: "5m"
  secretStoreRef:
    name: mainframe-vault-store
    kind: SecretStore
  target:
    name: api-to-splunk-secrets
    creationPolicy: Owner
  data:
    - secretKey: SPLUNK_HEC_TOKEN
      remoteRef:
        key: "secret/mainframe/splunk/hec"
        property: hec_token
    - secretKey: HMC_PRIMARY_USERNAME
      remoteRef:
        key: "secret/mainframe/hmc/primary"
        property: hmc_primary_user
    - secretKey: HMC_PRIMARY_PASSWORD
      remoteRef:
        key: "secret/mainframe/hmc/primary"
        property: hmc_primary_pass
    - secretKey: HMC_BACKUP_USERNAME
      remoteRef:
        key: "secret/mainframe/hmc/backup"
        property: hmc_backup_user
    - secretKey: HMC_BACKUP_PASSWORD
      remoteRef:
        key: "secret/mainframe/hmc/backup"
        property: hmc_backup_pass
    - secretKey: DS_MAIN_USERNAME
      remoteRef:
        key: "secret/mainframe/ds/main"
        property: ds_main_user
    - secretKey: DS_MAIN_PASSWORD
      remoteRef:
        key: "secret/mainframe/ds/main"
        property: ds_main_pass
    - secretKey: DS_DR_USERNAME
      remoteRef:
        key: "secret/mainframe/ds/dr"
        property: ds_dr_user
    - secretKey: DS_DR_PASSWORD
      remoteRef:
        key: "secret/mainframe/ds/dr"
        property: ds_dr_pass
    - secretKey: CSM_MAIN_USERNAME
      remoteRef:
        key: "secret/mainframe/csm/main"
        property: csm_main_user
    - secretKey: CSM_MAIN_PASSWORD
      remoteRef:
        key: "secret/mainframe/csm/main"
        property: csm_main_pass
    - secretKey: CSM_DR_USERNAME
      remoteRef:
        key: "secret/mainframe/csm/dr"
        property: csm_dr_user
    - secretKey: CSM_DR_PASSWORD
      remoteRef:
        key: "secret/mainframe/csm/dr"
        property: csm_dr_pass
    - secretKey: TS7700_PRIMARY_USERNAME
      remoteRef:
        key: "secret/mainframe/ts7700/primary"
        property: ts7700_primary_user
    - secretKey: TS7700_PRIMARY_PASSWORD
      remoteRef:
        key: "secret/mainframe/ts7700/primary"
        property: ts7700_primary_pass
    - secretKey: TS7700_BACKUP_USERNAME
      remoteRef:
        key: "secret/mainframe/ts7700/backup"
        property: ts7700_backup_user
    - secretKey: TS7700_BACKUP_PASSWORD
      remoteRef:
        key: "secret/mainframe/ts7700/backup"
        property: ts7700_backup_pass
