image:
  registry: ghcr.io
  repository: yonatan895/site_mon/site-mon
  tag: latest
  pullPolicy: IfNotPresent

replicaCount: 2

poller:
  resources:
    requests:
      cpu: 200m
      memory: 512Mi
    limits:
      cpu: 1000m
      memory: 1Gi

config:
  logLevel: "WARNING"
  hec:
    ackEnabled: true

pvc:
  size: "5Gi"

pdb:
  minAvailable: 1
